#!/bin/bash
# Quick optimization runner for Nemotrades

echo "🚀 Nemotrades Portfolio Optimizer"
echo "=================================="
echo ""
echo "Current Status:"
echo "  MAR: 208.6"
echo "  MDD: 18.2%"
echo "  Kelly: 0.70"
echo ""
echo "Target:"
echo "  MAR: > 220"
echo "  MDD: ≤ 18%"
echo ""
echo "=================================="
echo ""
echo "📋 TOP 3 CHANGES (Do These First):"
echo ""
echo "1. 🔥 McRib Deluxe: 0.8% → 2.5%"
echo "   Highest MAR strategy - severely under-allocated!"
echo ""
echo "2. ⭐ Iron Condor: 4% → 6%"
echo "   Tighten delta 30→25, widen wings 10→15"
echo ""
echo "3. 🛑 Pause 10 day RiC - 2"
echo "   Lowest MAR (4.2) - dragging portfolio down"
echo ""
echo "Expected Impact:"
echo "  MAR: 208.6 → 235-250 (+26 to +41)"
echo "  MDD: 18.2% → 17.5% (-0.7%)"
echo ""
echo "=================================="
echo ""
echo "Open implementation plan?"
read -p "Press Enter to open IMPLEMENTATION_PLAN.md..."

open IMPLEMENTATION_PLAN.md
